apiVersion: v1
kind: Namespace
metadata:
  name: team-b-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: team-b-test
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-server
        image: kennethreitz/httpbin
        ports:
        - name: http
          containerPort: 80
        - name: metrics
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: team-b-test
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: team-b-test
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`team-b.k3s-cluster.local`)
      kind: Rule
      services:
        - name: api-service
          port: 80
    - match: Host(`metrics.team-b.k3s-cluster.local`)
      kind: Rule
      services:
        - name: api-service
          port: 8080
  tls:
    # cert-manager will handle certificates for both hostnames
    secretName: api-metrics-example-com-tls # Cert for both api.example.com and metrics.example.com