apiVersion: v1
kind: Namespace
metadata:
  name: platform-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-admin-sa
  namespace: platform-team # Or the namespace where you want this SA to reside
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-sa-cluster-admin
  namespace: platform-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Binds to the predefined cluster-admin role
subjects:
- kind: ServiceAccount
  name: my-admin-sa
  namespace: platform-team # Must match the SA's namespace  
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-admin-sa-token
#   namespace: platform-team
#   annotations:
#     kubernetes.io/service-account.name: my-admin-sa # Link to your Service Account
# type: kubernetes.io/service-account-token
