apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-readonly-sa
  namespace: platform-team # Or the namespace where you want this SA to reside
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-access
  namespace: platform-team 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["*"]
  verbs: ["get"]
# - apiGroups: [""] # "" indicates the core API group
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["apps"]
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["networking.k8s.io"]
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["admissionregistration.k8s.io"] # For webhooks
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["apiextensions.k8s.io"] # For CRDs
#   resources: ["customresourcedefinitions"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["cert-manager.io"] # For cert-manager resources
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["capsule.clastix.io"] # For Capsule resources
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["kyverno.io"] # For Kyverno resources
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
# - apiGroups: ["monitoring.coreos.com"] # For Prometheus/Grafana resources
#   resources: ["*"]
#   verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-viewer-binding
subjects:
- kind: ServiceAccount
  name: my-readonly-sa
  namespace: platform-team  # The namespace where your service account was created
roleRef:
  kind: ClusterRole
  name: readonly-access
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-readonly-sa-token
#   namespace: default
#   annotations:
#     kubernetes.io/service-account.name: my-readonly-sa # Link to your Service Account
# type: kubernetes.io/service-account-token
